trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: Linux
    displayName: Build & Test Linux
    pool: 
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      displayName: "Use .NET 3.x"
      inputs:
        version: '3.x'
        packageType: sdk
    
    - task: DotNetCoreCLI@2
      displayName: 'Publish artifacts'
      inputs:
        command: publish
        projects: '**/src/TRH/*.csproj'
        arguments: '-c $(buildConfiguration) -r linux-x64 -o $(Build.SourcesDirectory)/artifacts/'

