trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: Linux
    displayName: Build & Test Linux
    pool: 
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'
      artifactsFolder: '$(Build.SourcesDirectory)/artifacts/'

    steps:
    - script: sudo apt-get install clang zlib1g-dev libkrb5-dev libtinfo5 -y
      displayName: Install requirements
      
    - task: UseDotNet@2
      displayName: "Use .NET 3.x"
      inputs:
        version: '3.x'
        packageType: sdk
    
    - powershell: dotnet publish -c $(buildConfiguration) -r linux-x64 -o $(artifactsFolder)
      displayName: 'Publish artifacts'

    - script: mv TRH trh
      displayName: Rename artifact
      workingDirectory: '$(artifactsFolder)'

    - script: strip trh
      displayName: Strip artifact
      workingDirectory: '$(artifactsFolder)'

    - script: ls -lah
      displayName: Debug artifacts
      workingDirectory: '$(artifactsFolder)'