# Created with YamlCreate.ps1 v2.0.0 $debug=NVS0.5-1-19041-1237
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GDATA.TypeRefHasher
PackageVersion: 1.0.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
UpgradeBehavior: install
Commands:
- trh
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GDATASoftwareAG/TypeRefHasher/releases/download/v1.0.0/trh.msi
  InstallerSha256: E308F5199F4F4972252784DD6B8A39CB542A566B1B75E040F130388E177F5E0B
  ProductCode: "{36DF3DA8-5511-45F0-B4C2-A63BD5B16041}"
ManifestType: installer
ManifestVersion: 1.0.0
