
PackageIdentifier: GDATA.TypeRefHasher
PackageVersion: 1.0.0
PackageName: TypeRefHasher
Publisher: G DATA CyberDefense AG
License: Apache 2
LicenseUrl: https://raw.githubusercontent.com/GDATASoftwareAG/TypeRefHasher/master/LICENSE
Moniker: trh
Tags:
- .net
- typerefhash
- trh
- imphash
ShortDescription: CLI tool to compute the TypeRefHash for .NET binaries.
PackageUrl: https://github.com/GDATASoftwareAG/TypeRefHasher
Commands:
- trh
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GDATASoftwareAG/TypeRefHasher/releases/download/v1.0.0/trh.msi
  InstallerSha256: E308F5199F4F4972252784DD6B8A39CB542A566B1B75E040F130388E177F5E0B
  InstallerType: msi
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0