# Created with YamlCreate.ps1 v2.0.0 $debug=NVS0.5-1-19041-1237
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: GDATA.TypeRefHasher
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: G DATA CyberDefense AG
PublisherUrl: https://github.com/GDATASoftwareAG
PublisherSupportUrl: https://github.com/GDATASoftwareAG/TypeRefHasher/issues
# PrivacyUrl: 
# Author: 
PackageName: TypeRefHasher
PackageUrl: https://github.com/GDATASoftwareAG/TypeRefHasher
License: Apache 2
LicenseUrl: https://raw.githubusercontent.com/GDATASoftwareAG/TypeRefHasher/master/LICENSE
# Copyright: 
# CopyrightUrl: 
ShortDescription: CLI tool to compute the TypeRefHash for .NET binaries.
# Description: 
Moniker: trh
Tags:
- .net
- typerefhash
- trh
- imphash
ManifestType: defaultLocale
ManifestVersion: 1.0.0
