# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GDATA.TypeRefHasher
PackageVersion: 1.0.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
UpgradeBehavior: install
Commands:
- trh
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GDATASoftwareAG/TypeRefHasher/releases/download/v1.0.3/trh.msi
  InstallerSha256: 1CF20CA66DCDFDA4007D5B27CEABC81BA8866926E91BB943F6DCC0240810571D
ManifestType: installer
ManifestVersion: 1.0.0

