# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: GDATA.TypeRefHasher
PackageVersion: 1.0.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
UpgradeBehavior: install
Commands:
- trh
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GDATASoftwareAG/TypeRefHasher/releases/download/v1.0.2/trh.msi
  InstallerSha256: 90F7ED58AF96932DE919FB59C7E7B387635EA1F8E3B3C88B29BF781F1EA862AD
ManifestType: installer
ManifestVersion: 1.0.0
